/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	float a;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
	int n;
};
typedef struct data data;

struct res_nums {
	float a_res;
	int maxmin[2];
	struct {
		u_int Y_len;
		float *Y_val;
	} Y;
};
typedef struct res_nums res_nums;

#define CALC_PROG 0x23451111
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define Average 1
extern  struct res_nums * average_1(data *, CLIENT *);
extern  struct res_nums * average_1_svc(data *, struct svc_req *);
#define MaxMin 2
extern  struct res_nums * maxmin_1(data *, CLIENT *);
extern  struct res_nums * maxmin_1_svc(data *, struct svc_req *);
#define VectorProduct 3
extern  struct res_nums * vectorproduct_1(data *, CLIENT *);
extern  struct res_nums * vectorproduct_1_svc(data *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Average 1
extern  struct res_nums * average_1();
extern  struct res_nums * average_1_svc();
#define MaxMin 2
extern  struct res_nums * maxmin_1();
extern  struct res_nums * maxmin_1_svc();
#define VectorProduct 3
extern  struct res_nums * vectorproduct_1();
extern  struct res_nums * vectorproduct_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_res_nums (XDR *, res_nums*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_res_nums ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
